# Generated by Django 4.1.7 on 2023-03-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, default=None, null=True, upload_to='categories_picture/', verbose_name='изображение категории')),
                ('alt', models.CharField(max_length=200, verbose_name='описание изображения')),
            ],
            options={
                'verbose_name': 'фотография категории',
                'verbose_name_plural': 'фотографии категорий',
            },
        ),
    ]
