# Generated by Django 4.1.7 on 2023-03-30 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=50, verbose_name='автор отзыва')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='email автора')),
                ('text', models.TextField(default='', max_length=500, verbose_name='текст отзыва')),
                ('rate', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка товара')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата отзыва')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
