# Generated by Django 4.1.7 on 2023-03-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='product_picture/', verbose_name='изображение товара')),
                ('alt', models.CharField(max_length=200, verbose_name='описание изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'фотография товара',
                'verbose_name_plural': 'фотографии товаров',
            },
        ),
    ]
