# Generated by Django 4.1.7 on 2023-03-30 19:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена')),
                ('count_in_stock', models.IntegerField(verbose_name='количество в наличии')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.CharField(max_length=150, verbose_name='краткое описание')),
                ('fullDescription', models.TextField(verbose_name='полное описание')),
                ('freeDelivery', models.BooleanField(default=False, verbose_name='бесплатная доставка')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('limited', models.BooleanField(default=False, verbose_name='ограниченный тираж')),
                ('available', models.BooleanField(default=True, verbose_name='в наличии')),
                ('category', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.category', verbose_name='категория товара')),
                ('images', models.ManyToManyField(blank=True, related_name='product_image', to='frontend.productimage', verbose_name='изображения товара')),
                ('reviews', models.ManyToManyField(blank=True, related_name='product_reviews', to='frontend.review', verbose_name='отзывы')),
                ('specifications', models.ManyToManyField(blank=True, related_name='product_specs', to='frontend.specifications', verbose_name='дополнительные характеристики')),
                ('tags', models.ManyToManyField(blank=True, related_name='product_tags', to='frontend.tag', verbose_name='тег')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
