# Generated by Django 4.1.7 on 2023-03-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_saleproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Обычная', 'Обычная'), ('Экспресс', 'Экспресс'), ('Корзина', 'Корзина')], max_length=100, verbose_name='название величины')),
                ('money', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='сумма')),
                ('description', models.TextField(max_length=100, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'стоимость доставки',
                'verbose_name_plural': 'стоимости доставки',
            },
        ),
    ]
