# Generated by Django 4.1.7 on 2023-03-30 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0010_order_orderproducts_order_products_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='номер карты')),
                ('name', models.CharField(max_length=150, verbose_name='имя держателя карты')),
                ('month', models.CharField(max_length=2, verbose_name='месяц')),
                ('year', models.CharField(max_length=4, verbose_name='год')),
                ('code', models.CharField(max_length=10, verbose_name='cvv код')),
                ('status', models.BooleanField(default=False, verbose_name='статус оплаты')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('paid_for', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='сумма платежа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='frontend.order', verbose_name='заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
