# Generated by Django 4.1.7 on 2023-03-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_basket_basketproducts_basket_products_basket_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketproducts',
            options={'verbose_name': 'товар из корзины', 'verbose_name_plural': 'все товары из корзины'},
        ),
    ]
