# Generated by Django 4.1.7 on 2023-03-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_alter_basketproducts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_subcategory',
            field=models.BooleanField(default=False, verbose_name='является подкатегорией'),
        ),
    ]
