# Generated by Django 4.1.7 on 2023-04-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_subcategory',
            field=models.BooleanField(default=True, help_text='Для выбора подкатегорий необходимо снять галочку и сохранить выбор. После обновления страницы откроется доступ к подкатегориям', verbose_name='является подкатегорией'),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='стоимость товаров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена со скидкой'),
        ),
    ]
