# Generated by Django 4.1.7 on 2023-04-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_alter_category_is_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.BooleanField(default=False, verbose_name='баннер на главной странице'),
        ),
    ]
