# Generated by Django 4.1.7 on 2023-03-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='file',
            new_name='src',
        ),
        migrations.AddField(
            model_name='avatar',
            name='alt',
            field=models.CharField(default=123, max_length=200, verbose_name='описание изображения'),
            preserve_default=False,
        ),
    ]
