# Generated by Django 4.1.7 on 2023-03-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_avatar_created_at_alter_avatar_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Аватарка', 'verbose_name_plural': 'Аватарки'},
        ),
    ]
